const PROJECT_CONFIG = require('./../../_config/project')

module.exports = {
  MOLECULE_FACTORY: PROJECT_CONFIG.MOLECULE_FACTORY,
  QUARKS_PATH: PROJECT_CONFIG.QUARKS_PATH,
  ATOMS_PATH: PROJECT_CONFIG.ATOMS_PATH
}
